In [1]:
#Importing Torch
import torch

In [2]:
# Check If I have GPU available or not
if torch.cuda.is_available():
    print("GPU Available")
    print(f"name : {torch.cuda.get_device_name(0)}")
    print(f"Memory : {torch.cuda.get_device_properties(0).total_memory}")
else:
    print("GPU Not Available")

GPU Available
name : Tesla T4
Memory : 15835660288


# Creating Tensor from pytorch

In [3]:
a = torch.empty(2, 3)
type(a) # this will show the type 

torch.Tensor

In [4]:
torch.zeros(2, 3) # all the values will be zero
torch.ones(2, 3) # all the values will be zero

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.rand(2, 3) # random number between 0 and 1

tensor([[0.1737, 0.5532, 0.2311],
        [0.1187, 0.1508, 0.8626]])

In [6]:
torch.manual_seed(100) # this will keep generate same random number
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) # tensor from specific value

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
torch.arange(0, 10, 2) # tensor value from 0 to <10 and leap will be 2

tensor([0, 2, 4, 6, 8])

In [9]:
torch.linspace(0, 100, 10) # silimer to arange

tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])

In [10]:
torch.eye(5) # return Identity matrix of sie n*n

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.full((3, 3), 5) # make all the value same 

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [12]:
# determining the shape of the tensor
a = torch.rand(3, 3)
a.shape # return the shape of the tensor

torch.Size([3, 3])

In [13]:
torch.empty_like(a) # make another tensor similer shape of the tensor a(show empty value)

tensor([[0.0000e+00, 0.0000e+00, 1.8788e+31],
        [1.7220e+22, 2.1715e-18, 3.3587e-06],
        [1.0693e-05, 5.4212e-05, 1.7265e-07]])

In [14]:
torch.rand_like(a, dtype=torch.float32) #make same shape tensor initialised with random value

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [15]:
torch.zeros_like(a) # same shape but all the values are 0
torch.ones_like(a) # same shape but all the values are 1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# Showing Datatype

In [16]:
a.dtype #show the type of tensor

torch.float32

In [17]:
torch.tensor([1, 2, 3], dtype=torch.int32)  # make tensor of specific type

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
a.to(torch.int32) # change the type of the tensor

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

# Basic Operation

In [19]:
a+2 # add 2 with all the element of a

a-2 # subtract 2 with all the element of a

a/2 # divid 2 with all the element of a

a*3 # multiply 3 with all the element of a

a//2 # integer divid 2 with all the element of a

(a*199) % 2 # find mod 

a**2 # power of 2

tensor([[0.0690, 0.0018, 0.0433],
        [0.0139, 0.0148, 0.5411],
        [0.5066, 0.6203, 0.1750]])

In [20]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

In [21]:
x+y # addition of 2 tensor

x-y # subtraction of 2 tensor

x/y # division of 2 vectors

x*y # multiplication of 2 vectors

x//y # integer division 

(x*199) % y # dont know

tensor([[0.2756, 0.0096, 0.1530],
        [0.0906, 0.2338, 0.1068],
        [0.8569, 0.1438, 0.0326]])

In [22]:
c = torch.tensor([1, -2, 3, -4])

torch.abs(c) # make all values position

torch.neg(c) # make all values negative

torch.round(c) # round if some value is float 

torch.exp(c) # find the exponential of all values

torch.log(c) # find logarithm

torch.sqrt(c) # find square root of all values

tensor([1.0000,    nan, 1.7321,    nan])

In [23]:
torch.clamp(c, min=-1, max=2) # bound all values within minimum and maximum value

tensor([ 1, -1,  2, -1])

In [24]:
e = torch.randint(size=(3, 3), low=5, high=10, dtype=torch.float32)

In [25]:
torch.sum(e) # return the sum of all values

tensor(68.)

In [26]:
torch.sum(e, dim=0) # return the sum of rows
torch.sum(e, dim=1) # return the sum of columns

tensor([23., 21., 24.])

In [27]:
torch.mean(e) # show mean of all values

tensor(7.5556)

In [28]:
torch.median(e) # show median of all values

tensor(8.)

In [29]:
torch.max(e) # show maximum of all values
torch.min(e) # show minimum of all alues

tensor(5.)

In [30]:
torch.prod(e) # product of all  values

tensor(64297800.)

In [31]:
torch.std(e) # standard daviasion of all values

tensor(1.6667)

In [32]:
torch.var(e) # variance of all values

tensor(2.7778)

In [33]:
torch.argmin(e) # position of minumum value

tensor(0)

In [34]:
torch.argmax(e) # position of maximum value 

tensor(1)

Matrix operatoon

In [35]:
p=torch.randint(size=(3, 3), low=5, high=9, dtype=torch.int32)
q=torch.randint(size=(3, 3), low=5, high=9, dtype=torch.int32)

In [36]:
torch.matmul(p, q) # multiplication of 2 tensor

tensor([[118, 150, 131],
        [113, 140, 128],
        [137, 170, 153]], dtype=torch.int32)

In [37]:
v1 = torch.tensor([1, 3, 2])
v2 = torch.tensor([3, 2, 1])

In [38]:
torch.dot(v1, v2) # docproduct of 2 tensors

tensor(11)

In [39]:
torch.transpose(x, 0, 1) # transpose of tensor

tensor([[0.4440, 0.4892, 0.5277],
        [0.9478, 0.2426, 0.2472],
        [0.7445, 0.7003, 0.7909]])

In [40]:
v1>v2 # show the list of  maximum value(boolean)

tensor([False,  True,  True])

In [41]:
v1<v2 # show the list of  minimum value(boolean)

tensor([ True, False, False])

In [43]:
k = torch.randint(size=(5, 5), low=9, high=21, dtype=torch.float32)

In [44]:
torch.sigmoid(k) # sigmopoid function

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.9999, 0.9999, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])

In [45]:
torch.relu(k) # relu function 

tensor([[14., 10., 13., 15., 16.],
        [11., 12., 13., 12., 15.],
        [12., 15., 16., 13., 16.],
        [10.,  9.,  9., 16., 17.],
        [18., 12., 11., 19., 11.]])

In [47]:
torch.softmax(k, dim=0) # softmax function

tensor([[1.7921e-02, 6.0768e-03, 4.4966e-02, 1.7094e-02, 1.9635e-01],
        [8.9222e-04, 4.4902e-02, 4.4966e-02, 8.5104e-04, 7.2234e-02],
        [2.4253e-03, 9.0188e-01, 9.0316e-01, 2.3134e-03, 1.9635e-01],
        [3.2823e-04, 2.2355e-03, 8.2358e-04, 4.6465e-02, 5.3374e-01],
        [9.7843e-01, 4.4902e-02, 6.0854e-03, 9.3328e-01, 1.3230e-03]])

inplace operation

In [51]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

In [49]:
m.add_ = m+n # inplace addition

In [50]:
m.relu_() # inplace relu function

tensor([[0.2499, 0.3206, 0.9753],
        [0.7582, 0.6688, 0.2651]])

# Copy 

In [52]:
n = m.clone() # Cloning a tensor

#tensor operation on GPU

In [53]:
torch.cuda.is_available() # check if GPU is available or not

True

In [54]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # storing GPU power into a variable

In [55]:
torch.rand((2, 3), device=device) # making a tensor and pushing it into GPU

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [56]:
m.to(device) # pushing into GPU

tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]], device='cuda:0')

In [58]:
import time
# writing the code with GPu power

n = 1000

matrix1 = torch.randint(size=(n, n), low=10, high=50, dtype=torch.int32)
matrix2 = torch.randint(size=(n, n), low=10, high=50, dtype=torch.int32)

#defining time
start_time = time.time()
on_cpu = torch.matmul(matrix1, matrix2)
end_time = time.time()-start_time

print(f"total time required : {end_time:.4f}")




total time required : 1.0497


In [60]:
import time
# writing the code with GPu power

n = 1000

matrix1 = torch.randint(size=(n, n), low=10, high=50, dtype=torch.float32)
matrix2 = torch.randint(size=(n, n), low=10, high=50, dtype=torch.float32)


matrix1 = matrix1.to(device)
matrix2 = matrix2.to(device)

#defining time
start_time = time.time()
on_cpu = torch.matmul(matrix1, matrix2)
end_time = time.time()-start_time

print(f"total time required : {end_time:.4f}")


total time required : 0.1267


In [62]:
m.shape

torch.Size([2, 3])

In [63]:
m.reshape(6, 1) # reshaping a tensor(Product of row and column must be equal for all shape)

tensor([[0.3397],
        [0.1879],
        [0.5534],
        [0.2682],
        [0.9556],
        [0.9761]])

In [64]:
#rearranging dimension
b = torch.rand(2, 3, 4)
b.permute(2, 1, 0) # rearranging column position (column index)

tensor([[[0.2027, 0.4021],
         [0.1142, 0.9557],
         [0.8186, 0.7711]],

        [[0.0298, 0.4723],
         [0.5151, 0.2597],
         [0.7866, 0.8058]],

        [[0.9324, 0.8623],
         [0.3628, 0.4822],
         [0.6962, 0.7985]],

        [[0.9879, 0.9867],
         [0.9032, 0.2435],
         [0.8758, 0.5763]]])

In [66]:
c = torch.rand(226, 226, 3) # convert a single image to batch
c.unsqueeze(0).shape # adding extra column into 0th index

torch.Size([1, 226, 226, 3])

In [67]:
c.squeeze(0).shape # adding column into 0th index

torch.Size([226, 226, 3])

In [68]:
# conversion from numpy to pytorch
import numpy as np

In [69]:
a = torch.tensor([1, 2, 3, 4, 5])
a.numpy() # convert to numpy

array([1, 2, 3, 4, 5])

In [ ]:
c = np.array([1, 2, 3, 4, 5])
torch.from_numpy(c) # convert to pytorch